name: Check
on: push

permissions: {}

env:
  NIX_DEV: nix develop --no-update-lock-file .#ci --command

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # We will not perform any other git operations in this repo
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Install dependencies
        run: ${{ env.NIX_DEV }} pnpm install --frozen-lockfile

      - name: Check
        run: ${{ env.NIX_DEV }} pnpm run ci
