name: Check
on: push

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # We will not perform any other git operations in this repo
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Install dependencies
        run: nix develop --command pnpm install

      - name: Check
        run: nix develop --command pnpm run ci
